### ISSUE TITLE
Ask to obtain all the reduction sequences from the command-line

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#14]
Having an interactive "play" with the process is nice, but it would be useful to also have an option to simply list all possible reductions.

E.g., entering a process a. 0 | b.0 and asking "list all possible reduction sequences" should return

- a, b
- b, a

and possibly more complicated structures (such as (a, 0|b.0), (b, 0|0)), so that you can "see" the process unfolding.

A trick is, for a process such as a.(b+c), do you want to list

- a, b
- a, c

or 

- a (b, c)
 
or something of that sort. It _should_ not be too difficult to go from one to the other, and it may be useful to access both formats.

**Comment by aubertc** [comment]
Thinking about this issue: I believe the second option listed would be preferable (list all complete sequences, without compressions), particularly for testing purposes.

Coupled with https://github.com/peterbro1/RCCS_Impl/issues/16, this could give a way of testing "very programmatically" that all the execution paths can be explored, and that e.g. all paths can be rewinded to the origin of the process.

_However_, there may be better ways of implementing this than to have the option of listing all reduction sequences.

**Comment by peterbro1** [comment]
https://github.com/CinRC/IRDC-CCSK/commit/b0dd1fb43f10d25c1baea3f7f6f4f2dc6f037ecc

This can now be done with --enumerate, but there is no dedicated command

**Comment by aubertc** [comment]
That is _super_ nice.
