### ISSUE TITLE
Semantic versioning and coherent version number(s)

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#31]
It would be nice to adopt some [semantic versioning](https://semver.org/) in this project. I'm sure there are ways in github of having this type of information stored as a variable that occurs in the release and such, and can investigate if you would like.

**Comment by aubertc** [comment]
I believe this can be closed too?
Ideally, you would start working on a changelog file where you would record (at least some of?) the changes that comes with a new version.

**Comment by peterbro1** [comment]
I'm going to adopt semantic versioning soon. In the next release (easy enumeration and simulation testing), we will switch to this method. I will close it then

**Comment by aubertc** [comment]
In the same spirit, we _may_ want to protect the master branches, so that (for instance) edits would be made only through pull requests, or to make sure that [tests are succesful](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging) before we accept a change in the codebase.

More hassle for the programmer, but more guarantee that nothing will suddenly break the whole project.

**Comment by peterbro1** [comment]
I agree, this should be done especially if we are going to bring more programmers into the mix. That way, you or I would need to approve PRs for them to be merged

**Comment by aubertc** [comment]
Ok, so that will require some work (in this order, I believe):

- [ ] Fix the deployment (cf. https://github.com/CinRC/IRDC-CCSK/issues/37 ),
- [ ] Document the version numbering,
- [ ] Protect the main branch,
- [ ] Fine-tune the options for the protected branches,
- [ ] Document how a pull request can be made
- [ ] Automatically  create releases upon merged pull requests?

Not so sure about the last point. Any opinion / idea?

**Comment by aubertc** [comment]
When you get a chance, let me know if I can tick "Fine-tune the options for the protected branches". I believe you took care of that, but we'll need to spell it out somewhere.

**Comment by aubertc** [comment]
(This issue is a bit getting out of hand, but a good way of documenting all of that would have to be [guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and [links to tutorials](https://www.dataschool.io/how-to-contribute-on-github/) explaining how to contribute).

**Comment by peterbro1** [comment]
For the most part, I think there is some "implied competencies" when working on GitHub collaboratively. Some intricacies and specificities that apply to our repo uniquely would be worth documenting, but I think it would be a bit long-winded to explain how to sign into an account and create a fork.

**Comment by aubertc** [comment]
I agree, and believe that we can close this issue. What do you think, @peterbro1 ?

**Comment by peterbro1** [comment]
Yes! Closing now. Contributing.md contains information, and I'll update it to include semver
