### ISSUE TITLE
Sharing ownership of repository

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#34]
If you agree, I think this project should be hosted by an [organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations) instead of being linked to your personal account.

This will improve the durability and visibility of this project.

**Comment by peterbro1** [comment]
Of course, I think that's a good idea. Does AU (or any organizations that you are affiliated with that involve this research) have an organization account?

**Comment by aubertc** [comment]
I can clone the repo into https://github.com/CinRC/IRDC-CCSK but this will not import the issues, so I will delete it and ask that you migrate https://github.com/peterbro1/IRDC-CCSK/ , if that's ok with you.

**Comment by aubertc** [comment]
(For that, Settings -> (Stay in "General) -> Scroll down ->  "Transfer ownership"

**Comment by peterbro1** [comment]
Should I transfer it to the user "CinRC" ? I just want to make sure before doing it

**Comment by aubertc** [comment]
Yes, absolutely. Make sure you accepted my invitation in this organization, and you'll still be admin on that repo.

**Comment by peterbro1** [comment]
Ownership has been transferred.
