### ISSUE TITLE
Documenting how to exit the program

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#54]
As of now, the command-line interface can only be terminated using CTRL + C, or equivalent commands.
We could either:

- Document how to exit the program (that is, kill it),
- Add a way to quit the program 

As a bonus, we could add a command to restart with a different process.

**Comment by peterbro1** [comment]
@aubertc Let me know if this is sufficient!

**Comment by aubertc** [comment]
Yes that's perfect, thanks!
