### ISSUE TITLE
Make "letter process" different

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#55]
As of now, `P` and `Q` are seen as equivalent:

https://github.com/CinRC/IRDC-CCSK/blob/50b2b777fb1902592a46794e62045a5307ddae1b/src/test/java/tests/SimulationTest.java#L151-L165

However, it could be useful to treat them as different, so that we could e.g. distinguish between `a.P + b.Q` and `a.Q + b.P`, which would be now treated as equivalent, even if they should probably not be treated as such: at least, unless we know that `P` and `Q` are themselves equivalent, we should not assume that.

**Comment by aubertc** [comment]
Can we access this flag non-interactively? Ideally, for this fix to be complete and tested, we should have test cases that check that with this `hasSameProcess` / the `--process-names-equivalent` flag set to true, then `P` and `Q` are not equivalent, and that with that flag set to false, they are equivalent (or the other way around, sorry if I read that wrong).

**Comment by peterbro1** [comment]
Yes, in the main class we loop through the program args. Each arg is matched to a flag and then added to a static array which serves as the "global config". Its recommended to clear this array before and after each test so as to not interfere with other tests or be interfered by others

**Comment by peterbro1** [comment]
Closing for now, as it's assumed closed. Please reopen if you find an issue
