### ISSUE TITLE
Parsing unreachable processes

### ISSUE THREAD

**Issue by aubertc** [CinRC/IRDC-CCSK#66]
The process "c.a[k].b.0" is not reachable, but the tool somehow makes it reachable by changing it to something actually meaningful:

```
java -jar target/IRDC-3.0.0.0-jar-with-dependencies.jar --interactive "c.a[k].b.0"
a[k]
------| Actionable Labels |------
[0] c
[1] [k1]
[q] Quit program
------------
a[k1].c.b
```

(with an additional weird bug that makes it display first a[k], then a[k1].c.b).

The expected behaviour (and this is related to https://github.com/CinRC/IRDC-CCSK/issues/22 ) would be to "reject" it.

**Comment by aubertc** [comment]
This issue resurfaced…

```
java -jar target/IRDC-4.1.1.1-jar-with-dependencies.jar "b.a[k1].0"
a[k0].b (Depth: 0), []
└─b─ a[k0].b[k1].0 (Depth: 1), [b]
```

**Comment by aubertc** [comment]
> "b.a[k1].0"

I still get this issue?

**Comment by peterbro1** [comment]
Fixed. That bug got reintroduced during parser v2 merge.
